# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      # (ERR_OSSL_EVP_UNSUPPORTED) typically arises because Node.js is using OpenSSL 3.x, which has stricter defaults. Some libraries, such as webpack or older dependencies, may not yet be compatible with these stricter OpenSSL 3.x settings.
      # NODE_OPTIONS=--openssl-legacy-provider ng deploy

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build Angular app
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build -- --base-href "/my-first-project/"
     #base-href in an Angular app defines the root path for resolving relative URLs to assets (CSS, JS, etc.). 
     #By default, Angular apps assume they are hosted at the root (/). 
     #The trailing slash at the end of base-href is important.
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./dist/my-first-project
      #Check outputPath in  angular.json file
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/my-first-project